### PR TITLE
Feature: segger 20pin

### PR DESCRIPTION
**Pull request by perigoso**
Draft because it was just a quick and dirty addition and more text context can be added, and I don't know if it belongs as currently the glossary is about target connectors and this is a debug probe connector, though it would be useful when using a J-Link via BMDA

### CODE REVIEW

**Comment by esden** [comment]
I think this is indeed useful. Not just in the BMDA situation but also when people try to connect BMP to targets that were using J-Link before. So yes I would like to add this to the docs.

**Comment by esden** [comment]
Ok let's give it a try 🤞 :D

**Comment by perigoso** [comment]
For review and future reference, this official doc contains pinout for both JTAG and SWD: [UM08001_JLinkARM](https://github.com/blackmagic-debug/black-magic-org/files/12188277/UM08001_JLinkARM.pdf) (I don't know how trustworthy GH is with uploaded files, but the doc can be found through the name/reference too)

**Comment by perigoso** [comment]
Addtional note, that may be useful to add as a note later, the 1bit2 20pin adapter does allow using the J-Link probe with BMDU connector targets, with the exception of the 5V supply pin

**Comment by esden** [comment]
Ohh good to know. Yes it would be useful information to have it in the docs.

**Pull request merged**
