### PR TITLE
Update Windows build instructions

### PR DESCRIPTION
**Pull request by rhempel**
- The pacboy package is available in the pactoys package
- A bare-bones Docker image with Python3 may need to install python3-tk

### CODE REVIEW

**Comment by dragonmux** [comment]
👋🏼 Interesting point about python3-tk - wasn't aware of that!

The Windows side of this PR duplicates [our patch in #45](https://github.com/blackmagic-debug/black-magic-org/pull/45/commits/6c83f4c3d1baf512358f3f3b1ef6632356bef00a) - If you could at least split the two changes to the README.md and the Windows guide into separate commits at least, it'll help in handling this.

**Comment by rhempel** [comment]
Thanks for the feedback - I'll split the commits and force-push into my branch again, if that's OK with you.

With just `blackmagic.exe` pulled out of MSYS2, it complained about missing `libusb-1.0.dll` and `hidapi-0.dll`.

For my situation, the corporate laptops don't allow installing things like MSYS2, but as developers we can just copy executables :-) Go figure.

I tried to copy out just `blackmagic.exe` and `ftd2xx.dll` and `blackmagic` complained about not finding the other dlls. Remember, I'm trying to make a minimally invasive Windows installation for just BMDA - this is for my Docker/VSCode cortex environment described here:

https://github.com/rhempel/adaptabuild-example

The current implementation needs a Windows install of `st-util` and `openocd` and it's not as reliable as I would like, So far the BDMA words with my Nucleo targets and I hope to get it working this week with my NRF and Pico target boards.

I'm just working through the `cortex-debug` launch scripts for supporting BDMA as an external debugger over a socket to the Docker container.

That's probably more information than you want today - but so far I'm loving BDMA and hope to get a BlackMagic probe (and probably a Glasgow interface) in the near future.

**Comment by dragonmux** [comment]
> I tried to copy out just blackmagic.exe and ftd2xx.dll and blackmagic complained about not finding the other dlls.

That problem is why we mention building BMDA with those other dependencies not installed (or using `--force-override-for=libusb,hidapi` on the `meson setup build` line or after with `meson configure` in the build directory). If Meson finds those dependencies on the host machine, it'll dynamically link them. If it does not (or you force use of the subproject fallbacks), it will build them statically and statically link them.

**Comment by rhempel** [comment]
I'm not building BDMA or BlackMagic firmware using the Meson system - I'm building BDMA from MSYS2/UCRT64 on WIndows with this line:

`mingw32-make PROBE_HOST=hosted HOSTED_BMP_ONLY=0`

I tried (really I did) to use Meson on my Docker Ubuntu 22.04 machine but my cross-compile file was probably messed up.

**Comment by dragonmux** [comment]
Ah, okie, the Makefile build system has no ideas about static linking those dependencies and such - if you were to try from in your MSYS2 environment then it's `meson setup build` to get just BMDA. Cross-compiling to Windows is a bit of a pain (requires xwin or cargo-xwin to get the headers and libraries needed + clang-cl or so to target Windows with).

Using Meson under MSYS2 is as simple as `pacboy -S meson:p` to get Meson, and then proceeding with Meson in place of Make per the main repo README.md. The Windows instructions weren't yet updated for this because it only works on `main`, not the 1.x series releases.

**Comment by rhempel** [comment]
Thanks for the additional background details - cross compiling is always a pain and MSYS2 just (mostly) works so I'm fine with that step.

By the way, so far BDMA is working great for me - at the risk of being the "old embedded guy with 40 years experience" it's really refreshing to see so much open source in the embedded world, and young people ready to lean in on it. Back in the old days (here we go) debugging embedded meant buying a compiler per developer, buying one In Circuit Emulator at between 10-20K to share between developers, no git, not much in the way of good unit test frameworks, etc.

I'm just sorting out a few things with getting BDMA set up as a GDB external target for my Docker/VSCode system and then I'll contribute the learnings to the cortex-debug plugin team.

Thanks again for such an awesome project.

**Comment by dragonmux** [comment]
Could you please rebase this PR on `main` and update the note about which binaries to copy to include `ftd2xx.dll` and then we'll get this merged.

**Comment by rhempel** [comment]
Done - and just for completeness I verified the instructions on a clean install of msys2 :-)

**Comment by ALTracer** [comment]
Likewise, I just went through a clean install of Msys2 UCRT64 on my Windows 11 laptop, and recorded a few commands. The strip and dll copying steps are relevant for Makefile builds. I assume meson builds will be documented later. Both work.

I've been using this method to deploy BMDA I built on one Win7 machine to another in a fairly compact zip, no full Msys2 required. Also this is much more self-contained than full OpenOCD.

**Comment by esden** [comment]
Thank you all! Thank you for testing updating and testing.

**Pull request merged**
